// src/app/layout.js
import './globals.css'; // Adjust path if needed
import Navigation from '../components/Global/Navigation';
import Footer from '../components/Global/Footer';
import AIChatModal from '../components/Global/AIChatModal'
export const metadata = {
  title: 'Skyline Sprint',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <main>{children}</main>
        <AIChatModal/>
        <Footer />
      </body>
    </html>
  );
}
